arch:
  - amd64

matrix:
  include:

    - language: generic
      os: osx
      osx_image: xcode11.3
      before_install:
        - python3 --version
      install:
        - pip3 install -r requirements.txt
      before_script:
      script:
        - cd ${TRAVIS_BUILD_DIR}/erdpy/tests
        - erdpy config set dependencies.elrond_proxy_go.tag fix-node-ref
        - source ./test_cli_testnet.sh && testStart


