matrix:
  include:
    - language: python
      os: linux
      install:
        - pip3 install -r requirements.txt
      before_script:
      script:
        - make test-short

    - language: python
      os: osx
      osx_image: xcode11.3
      install:
        - pip3 install -r requirements.txt
      before_script:
      script:
        - make test-short
